-- Drop tables that have foreign key dependencies first:
DROP TABLE FEATURED_ITEMS CASCADE CONSTRAINTS;
DROP TABLE PROMOTIONS CASCADE CONSTRAINTS;
DROP TABLE ITEM_OPTIONS CASCADE CONSTRAINTS;
DROP TABLE MENU_ITEMS CASCADE CONSTRAINTS;
DROP TABLE MENU_SECTIONS CASCADE CONSTRAINTS;
DROP TABLE DELIVERY_OPTIONS CASCADE CONSTRAINTS;
DROP TABLE RESTAURANT_SCHEDULES CASCADE CONSTRAINTS;
DROP TABLE RESTAURANTS CASCADE CONSTRAINTS;

-- If you want to verify each table is gone, you can do:
-- SELECT table_name FROM user_tables WHERE table_name IN (
--   'RESTAURANTS','RESTAURANT_SCHEDULES','DELIVERY_OPTIONS','MENU_SECTIONS',
--   'MENU_ITEMS','ITEM_OPTIONS','PROMOTIONS','FEATURED_ITEMS'
-- );
