-- Create the sequence for CUSTOMER_ID
CREATE SEQUENCE customers_seq
  START WITH 1      -- first value returned
  INCREMENT BY 1    -- how much to add each time
  NOCACHE           -- don’t preallocate values in memory
  NOCYCLE;          -- stop if you exceed MAXVALUE

-- Insert statements for the CUSTOMERS table
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Maryam', 'Ali', '9599 Market St SW', '', '', 'Seattle', 'WA', '98103', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Alessandro', 'Bianchi', '6707 Aurora Ave N', '', '', 'Seattle', 'WA', '98154', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Chiara', 'Ferrari', '4527 Yesler Way W', '', '', 'Seattle', 'WA', '98134', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Wei', 'Li', '310 1st Ave SE', '', '', 'Seattle', 'WA', '98107', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Stefan', 'Fischer', '3374 3rd Ave SW', 'Apt 495', '', 'Seattle', 'WA', '98121', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Marco', 'Ricci', '508 Pine St S', 'Apt 119', '', 'Seattle', 'WA', '98103', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Mary', 'Smith', '6026 3rd Ave N', '', '', 'Seattle', 'WA', '98154', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Anna', 'Schmidt', '1272 Aurora Ave SW', 'Apt 326', '', 'Seattle', 'WA', '98106', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Robert', 'Wilson', '7388 Aurora Ave W', '', '', 'Seattle', 'WA', '98199', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Ingrid', 'Becker', '770 Madison St W', '', '', 'Seattle', 'WA', '98108', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Aisha', 'Farouk', '271 Aurora Ave E', '', '', 'Seattle', 'WA', '98102', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'John', 'Clark', '3998 Aurora Ave S', '', '', 'Seattle', 'WA', '98154', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Qing', 'Li', '5302 Aurora Ave S', '', '', 'Seattle', 'WA', '98106', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Juan', 'Rodriguez', '2136 Yesler Way E', '', '', 'Seattle', 'WA', '98164', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Sakura', 'Tanaka', '9830 3rd Ave E', '', '', 'Seattle', 'WA', '98134', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Stefano', 'Gallo', '2256 Dexter Ave W', '', '', 'Seattle', 'WA', '98126', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Rei', 'Sato', '3278 3rd Ave W', '', '', 'Seattle', 'WA', '98116', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Stefano', 'Esposito', '9772 1st Ave', '', '', 'Seattle', 'WA', '98116', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Sandeep', 'Gupta', '2045 Pine St SW', '', '', 'Seattle', 'WA', '98115', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Linda', 'Taylor', '8133 Broadway S', '', '', 'Seattle', 'WA', '98115', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Kumar', 'Gupta', '110 Yesler Way', '', '', 'Seattle', 'WA', '98144', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Hiroshi', 'Watanabe', '7027 Market St N', '', '', 'Seattle', 'WA', '98106', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE৩, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Aisha', 'Abbas', '6578 Dexter Ave W', 'Apt 275', '', 'Seattle', 'WA', '98199', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Abdullah', 'Abbas', '500 Union St W', '', '', 'Seattle', 'WA', '98101', 'USA', '');

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRSTNAME, LASTNAME, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, COUNTRY, PHONE_NUMBER)
VALUES (customers_seq.nextval, 'Daniel', 'Miller', '8221 Jackson St', '', '', 'Seattle', 'WA', '98107', 'USA', '');
